INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("Nintendo Switch", "Video Games", 299.00, 50);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("LoZ: Breath of the Wild", "Video Games", 59.00, 100);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("Nintendo Joy-Con", "Video Games", 79.99, 30);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("Play-Doh","Toys", 10.00, 25);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("T-Shirt", "Apparel", 15.00, 10);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("Ready Player One", "Movies", 19.99, 15);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("Deadpool 2", "Movies", 15.99, 20);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("Cards Against Humanity", "Games", 25.00, 50);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("Candy Land", "Games", 12.99, 20);
INSERT INTO products (product_name, department_name, price, stock_quantity) VALUES ("Levi's Jean", "Apparel", 25.00, 20);